version: "3.0"

services:
  web:
    image: ${npm_package_name}:${npm_package_version}
    volumes:
      - ./src:/usr/src/app
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - db
      - cache
  db:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - ./.data/mongodb:/data/db

  cache:
    image: redis:4.0
    ports:
      - "6379:6379"